### ISSUE TITLE
Segmentation fault while running the app

### ISSUE THREAD

**Issue by Suzie97** [lxmcf/virgil#8]
Hey, I compiled virgil from source and when I do `./libvirgil.so ` inside the build folder, a segmentation fault error is displayed.

I'm executing the right file right?

**Comment by lxmcf** [comment]
Hi there, VIrgil is just a library, as you have compiled a .so library, you will need to create a linked application, I have a [demo application ](https://github.com/lxmcf/virgil-demo) you can use to see Virgil in action.

I would just recommend reading the compilation steps, I'll go ahead and close this off now.

**Comment by Suzie97** [comment]
> 
> 
> Hi there, VIrgil is just a library, as you have compiled a .so library, you will need to create a linked application, I have a [demo application ](https://github.com/lxmcf/virgil-demo) you can use to see Virgil in action.
> 
> I would just recommend reading the compilation steps, I'll go ahead and close this off now.

Yeah, I checked that out yesterday. Nice work.

Thank you
